services:
  db:
    image: postgres:latest
    restart: always  # always restart the container
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - /tmp/postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_net

  pgbouncer:
    image: edoburu/pgbouncer
    restart: always
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - LISTEN_PORT=5432
      - AUTH_TYPE=scram-sha-256

    networks:
      - app_net
    depends_on:
      db:
        condition: service_healthy

  webapi_1:
    build: .
    ports:
      - "8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pgbouncer:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      db:
        condition: service_healthy
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    networks:
      - app_net

  webapi_2:
    extends:
      service: webapi_1


  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8000:80"
      - "8001:81"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - ./bankline-app/dist:/usr/share/nginx/html
    networks:
        - app_net
    depends_on:
      - webapi_1
      - webapi_2

networks:
  app_net:
    driver: bridge
