version: '3'


services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432"
    volumes:
      - /tmp/postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_net

  webapi_1:
    build: .
    ports:
      - "8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      db:
        condition: service_healthy
    deploy:
      replicas: 2
      restart_policy:
        condition: any
    networks:
      - app_net

  webapi_2:
    extends:
      service: webapi_1


  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
      - "8001:81"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - ./front_end:/usr/share/nginx/html
    networks:
        - app_net
    depends_on:
      - webapi_1
      - webapi_2

networks:
  app_net:
    driver: bridge
