apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployAppBank
  labels:
    app: deployAppBank
spec:
  replicas: 10
  selector:
    matchLabels:
      app: deployAppBank
  template:
    metadata:
      name: deployAppBank
      labels:
        app: deployAppBank
    spec:
      containers:
        - name: deployAppBank
          image: hellyaxs/santanabank:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
      