version: '3'

services:
    db:
        image: postgres:latest
        restart: always
        environment:
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_USER=postgres
          - POSTGRES_DB=postgres
        ports:
        - "5432:5432"
        volumes:
        - ./postgres-data:/var/lib/postgresql/data

    webApi_1:
        build: .
        ports:
          - "8080:8080"



    webApi_2:
      extends:
        service: webApi_1

    nginx:
      image: nginx:latest
      ports:
        - "80:80"
      volumes:
        - ./nginx:/etc/nginx/nginx.conf