version: '3'

services:
    db:
        image: postgres:9.6
        restart: always
        environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: postgres
        ports:
        - 5432:5432
        volumes:
        - ./postgres-data:/var/lib/postgresql/data

    webApi_1:
        build: ../..
        container_name: webApi_1


    webApi_2:
      extends:
        service: webApi_1

    nginx:
      image: nginx:latest
      conatiner_name: nginx
      ports:
        - 8000:80
      volumes:
        - ./nginx:/etc/nginx/nginx.conf