apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: app-bank
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      name: postgres
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: credentials-postgres
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-db
      restartPolicy: Always
      volumes:
        - name: postgres-db
          persistentVolumeClaim:
            claimName: postgres-pvc
---
kind: Service
apiVersion: v1
metadata:
  namespace: app-bank
  name: postgres-svc
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
  type: ClusterIP